/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CardRouteImport } from './routes/card'
import { Route as CreditRouteImport } from './routes/credit'
import { Route as CreditApprovedRouteImport } from './routes/credit-approved'
import { Route as CreditCheckRouteImport } from './routes/credit-check'
import { Route as CreditDeclinedRouteImport } from './routes/credit-declined'
import { Route as CreditFormRouteImport } from './routes/credit-form'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as InstallmentRouteImport } from './routes/installment'
import { Route as ProcessingRouteImport } from './routes/processing'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReceiptRouteImport } from './routes/receipt'
import { Route as ReceiptEmailRouteImport } from './routes/receipt-email'
import { Route as SbpRouteImport } from './routes/sbp'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ThanksRouteImport } from './routes/thanks'
import { Route as WaitingRouteImport } from './routes/waiting'
import { Route as YandexPayRouteImport } from './routes/yandex-pay'
import { Route as YandexSplitRouteImport } from './routes/yandex-split'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditRoute = CreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditApprovedRoute = CreditApprovedRouteImport.update({
  id: '/credit-approved',
  path: '/credit-approved',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditCheckRoute = CreditCheckRouteImport.update({
  id: '/credit-check',
  path: '/credit-check',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditDeclinedRoute = CreditDeclinedRouteImport.update({
  id: '/credit-declined',
  path: '/credit-declined',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditFormRoute = CreditFormRouteImport.update({
  id: '/credit-form',
  path: '/credit-form',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallmentRoute = InstallmentRouteImport.update({
  id: '/installment',
  path: '/installment',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingRoute = ProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptRoute = ReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptEmailRoute = ReceiptEmailRouteImport.update({
  id: '/receipt-email',
  path: '/receipt-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SbpRoute = SbpRouteImport.update({
  id: '/sbp',
  path: '/sbp',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ThanksRoute = ThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitingRoute = WaitingRouteImport.update({
  id: '/waiting',
  path: '/waiting',
  getParentRoute: () => rootRouteImport,
} as any)
const YandexPayRoute = YandexPayRouteImport.update({
  id: '/yandex-pay',
  path: '/yandex-pay',
  getParentRoute: () => rootRouteImport,
} as any)
const YandexSplitRoute = YandexSplitRouteImport.update({
  id: '/yandex-split',
  path: '/yandex-split',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/card': typeof CardRoute
  '/credit': typeof CreditRoute
  '/credit-approved': typeof CreditApprovedRoute
  '/credit-check': typeof CreditCheckRoute
  '/credit-declined': typeof CreditDeclinedRoute
  '/credit-form': typeof CreditFormRoute
  '/error': typeof ErrorRoute
  '/installment': typeof InstallmentRoute
  '/processing': typeof ProcessingRoute
  '/profile': typeof ProfileRoute
  '/receipt': typeof ReceiptRoute
  '/receipt-email': typeof ReceiptEmailRoute
  '/sbp': typeof SbpRoute
  '/success': typeof SuccessRoute
  '/support': typeof SupportRoute
  '/thanks': typeof ThanksRoute
  '/waiting': typeof WaitingRoute
  '/yandex-pay': typeof YandexPayRoute
  '/yandex-split': typeof YandexSplitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/card': typeof CardRoute
  '/credit': typeof CreditRoute
  '/credit-approved': typeof CreditApprovedRoute
  '/credit-check': typeof CreditCheckRoute
  '/credit-declined': typeof CreditDeclinedRoute
  '/credit-form': typeof CreditFormRoute
  '/error': typeof ErrorRoute
  '/installment': typeof InstallmentRoute
  '/processing': typeof ProcessingRoute
  '/profile': typeof ProfileRoute
  '/receipt': typeof ReceiptRoute
  '/receipt-email': typeof ReceiptEmailRoute
  '/sbp': typeof SbpRoute
  '/success': typeof SuccessRoute
  '/support': typeof SupportRoute
  '/thanks': typeof ThanksRoute
  '/waiting': typeof WaitingRoute
  '/yandex-pay': typeof YandexPayRoute
  '/yandex-split': typeof YandexSplitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/card': typeof CardRoute
  '/credit': typeof CreditRoute
  '/credit-approved': typeof CreditApprovedRoute
  '/credit-check': typeof CreditCheckRoute
  '/credit-declined': typeof CreditDeclinedRoute
  '/credit-form': typeof CreditFormRoute
  '/error': typeof ErrorRoute
  '/installment': typeof InstallmentRoute
  '/processing': typeof ProcessingRoute
  '/profile': typeof ProfileRoute
  '/receipt': typeof ReceiptRoute
  '/receipt-email': typeof ReceiptEmailRoute
  '/sbp': typeof SbpRoute
  '/success': typeof SuccessRoute
  '/support': typeof SupportRoute
  '/thanks': typeof ThanksRoute
  '/waiting': typeof WaitingRoute
  '/yandex-pay': typeof YandexPayRoute
  '/yandex-split': typeof YandexSplitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/card'
    | '/credit'
    | '/credit-approved'
    | '/credit-check'
    | '/credit-declined'
    | '/credit-form'
    | '/error'
    | '/installment'
    | '/processing'
    | '/profile'
    | '/receipt'
    | '/receipt-email'
    | '/sbp'
    | '/success'
    | '/support'
    | '/thanks'
    | '/waiting'
    | '/yandex-pay'
    | '/yandex-split'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/card'
    | '/credit'
    | '/credit-approved'
    | '/credit-check'
    | '/credit-declined'
    | '/credit-form'
    | '/error'
    | '/installment'
    | '/processing'
    | '/profile'
    | '/receipt'
    | '/receipt-email'
    | '/sbp'
    | '/success'
    | '/support'
    | '/thanks'
    | '/waiting'
    | '/yandex-pay'
    | '/yandex-split'
  id:
    | '__root__'
    | '/'
    | '/card'
    | '/credit'
    | '/credit-approved'
    | '/credit-check'
    | '/credit-declined'
    | '/credit-form'
    | '/error'
    | '/installment'
    | '/processing'
    | '/profile'
    | '/receipt'
    | '/receipt-email'
    | '/sbp'
    | '/success'
    | '/support'
    | '/thanks'
    | '/waiting'
    | '/yandex-pay'
    | '/yandex-split'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardRoute: typeof CardRoute
  CreditRoute: typeof CreditRoute
  CreditApprovedRoute: typeof CreditApprovedRoute
  CreditCheckRoute: typeof CreditCheckRoute
  CreditDeclinedRoute: typeof CreditDeclinedRoute
  CreditFormRoute: typeof CreditFormRoute
  ErrorRoute: typeof ErrorRoute
  InstallmentRoute: typeof InstallmentRoute
  ProcessingRoute: typeof ProcessingRoute
  ProfileRoute: typeof ProfileRoute
  ReceiptRoute: typeof ReceiptRoute
  ReceiptEmailRoute: typeof ReceiptEmailRoute
  SbpRoute: typeof SbpRoute
  SuccessRoute: typeof SuccessRoute
  SupportRoute: typeof SupportRoute
  ThanksRoute: typeof ThanksRoute
  WaitingRoute: typeof WaitingRoute
  YandexPayRoute: typeof YandexPayRoute
  YandexSplitRoute: typeof YandexSplitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit': {
      id: '/credit'
      path: '/credit'
      fullPath: '/credit'
      preLoaderRoute: typeof CreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-approved': {
      id: '/credit-approved'
      path: '/credit-approved'
      fullPath: '/credit-approved'
      preLoaderRoute: typeof CreditApprovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-check': {
      id: '/credit-check'
      path: '/credit-check'
      fullPath: '/credit-check'
      preLoaderRoute: typeof CreditCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-declined': {
      id: '/credit-declined'
      path: '/credit-declined'
      fullPath: '/credit-declined'
      preLoaderRoute: typeof CreditDeclinedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-form': {
      id: '/credit-form'
      path: '/credit-form'
      fullPath: '/credit-form'
      preLoaderRoute: typeof CreditFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installment': {
      id: '/installment'
      path: '/installment'
      fullPath: '/installment'
      preLoaderRoute: typeof InstallmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing': {
      id: '/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof ProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt': {
      id: '/receipt'
      path: '/receipt'
      fullPath: '/receipt'
      preLoaderRoute: typeof ReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt-email': {
      id: '/receipt-email'
      path: '/receipt-email'
      fullPath: '/receipt-email'
      preLoaderRoute: typeof ReceiptEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sbp': {
      id: '/sbp'
      path: '/sbp'
      fullPath: '/sbp'
      preLoaderRoute: typeof SbpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thanks': {
      id: '/thanks'
      path: '/thanks'
      fullPath: '/thanks'
      preLoaderRoute: typeof ThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiting': {
      id: '/waiting'
      path: '/waiting'
      fullPath: '/waiting'
      preLoaderRoute: typeof WaitingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yandex-pay': {
      id: '/yandex-pay'
      path: '/yandex-pay'
      fullPath: '/yandex-pay'
      preLoaderRoute: typeof YandexPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yandex-split': {
      id: '/yandex-split'
      path: '/yandex-split'
      fullPath: '/yandex-split'
      preLoaderRoute: typeof YandexSplitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardRoute: CardRoute,
  CreditRoute: CreditRoute,
  CreditApprovedRoute: CreditApprovedRoute,
  CreditCheckRoute: CreditCheckRoute,
  CreditDeclinedRoute: CreditDeclinedRoute,
  CreditFormRoute: CreditFormRoute,
  ErrorRoute: ErrorRoute,
  InstallmentRoute: InstallmentRoute,
  ProcessingRoute: ProcessingRoute,
  ProfileRoute: ProfileRoute,
  ReceiptRoute: ReceiptRoute,
  ReceiptEmailRoute: ReceiptEmailRoute,
  SbpRoute: SbpRoute,
  SuccessRoute: SuccessRoute,
  SupportRoute: SupportRoute,
  ThanksRoute: ThanksRoute,
  WaitingRoute: WaitingRoute,
  YandexPayRoute: YandexPayRoute,
  YandexSplitRoute: YandexSplitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
